# Generated by Django 3.0.4 on 2020-04-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='group/'),
        ),
        migrations.AddField(
            model_name='group',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='image',
            field=models.ImageField(blank=True, upload_to='group/'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
